# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b11c2190a00a2a2c1c42a3bd91f6bb957db91f01cac9ecb76229c65ffe1859d9d53c85587b96398eec50e7d41c45209ae4582e1068074ae570c689cc35dcf3e6

test:
  secret_key_base: 341c621ccba161352326cfd74926709e61215a825b194a3138236db9588bc445bc9d3b57bd54c1dc7293bd7c5d033bfa9ac6e430ce62abc651658ad3146f2e07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
