# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599c15db78dfedcc7d3fb4b74978524758f8f422b678f4bf393c504e5fbe348c1c9971b911eb832f5930bcbbaa0014cdc27011578b32893be37181c07260042b

test:
  secret_key_base: e85d60816396d6365d715fe3fcf67221a9fca4b3aebccc39b5d5727c630a09beef8a04637d37f192d14e9f0588d12264959236eb84b4417920a8696addb7a06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
