# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f584fa174acc2e00f6bb9141264519e79872d733ca6b2a9453fe7fad38c59acb295ec3cdb7dec53c2d4d079ce7e1f9b00ddfd04fb1051b4ddc8e3ef2ab406b6

test:
  secret_key_base: 953f8a5e4b0bd8dde8bf17809022eb0e747a13ddd736e57f57cfb75672d2d4759343c9e1148b905461b213c0b62793f1dcc8dc79712b64ddad519c351fd1597a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
